name = "newsnow" # 你的 Worker 名称，可以自定义，它会成为 Cloudflare 上的服务名称
compatibility_date = "2025-05-14" # 使用一个近期的日期，或者你开始项目时的日期

# 主 Worker 脚本的入口点
# Nitro 构建的服务器入口通常是 .output/server/index.mjs
main = "./dist/output/server/index.mjs"

# 静态资源配置
# Nitro 会将静态文件放在 .output/public 目录下
[site]
bucket = "./dist/output/public"

# 如果你的项目有 D1 数据库、KV 存储、R2 存储等绑定，也需要在这里配置
# 例如:
# [[d1_databases]]
# binding = "DB" # 在代码中访问数据库的名称
# database_name = "your-database-name"
# database_id = "your-database-id"

# [[kv_namespaces]]
# binding = "MY_KV"
# id = "your_kv_namespace_id"
# preview_id = "your_kv_namespace_preview_id" # 可选，用于本地开发预览
